### ISSUE TITLE
Problem on Persian calendar

### ISSUE THREAD

**Issue by ArashRahimian** [hogaf/Hogaf.ExtNet.UX#1]
Hi there.
Tanks about these useful controls but i have a problem. When i load these controls on a standalone window control everything works fine but when i load these controls on a page that must be loaded in desktop control i receive an error that tell me The resource can not be found. I find out that these controls can not find the embedded java scripts when they are used in a desktop control window. The problem is in this part of code:

[Description("")]
protected override List<ResourceItem> Resources
{
get
{
var baseList = base.Resources;
baseList.Capacity += 3;

baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex t.Net.extjs.PDate.pdate.js", ""));
baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex t.Net.extjs.PDate.picker.PMonth.js", ""));
baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex t.Net.extjs.PDate.picker.PDate.js", ""));

return baseList;
}
}

Client Script Item can not find embedded java scripts when these controls are used as a content of a windows that is contained in desktop control. How could I solve this problem?

**Comment by hogaf** [comment]
Hi,
Would you please provide me with a sample?! It's going to be much easier to
follow. I don't realy get what you mean by desktop control.


On Feb 17, 2017 21:57, "Arash Rahimian" <notifications@github.com> wrote:

Hi there.
Tanks about these useful controls but i have a problem. When i load these
controls on a standalone window control everything works fine but when i
load these controls on a page that must be loaded in desktop control i
receive an error that tell me The resource can not be found. I find out
that these controls can not find the embedded java scripts when they are
used in a desktop control window. The problem is in this part of code:

[Description("")]
protected override List Resources
{
get
{
var baseList = base.Resources;
baseList.Capacity += 3;

baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex
t.Net.extjs.PDate.pdate.js", ""));
baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex
t.Net.extjs.PDate.picker.PMonth.js",
""));
baseList.Add(new ClientScriptItem(typeof(PDatePicker),
"Diten.Web.UI.WebControls.PersianCalendar.Build.Ex
t.Net.extjs.PDate.picker.PDate.js",
""));

return baseList;
}
}

Client Script Item can not find embedded java scripts when these controls
are used as a content of a windows that is contained in desktop control.
How could I solve this problem?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hogaf/Hogaf.ExtNet.UX/issues/1>, or mute the thread

**Comment by ArashRahimian** [comment]
Hi. 
Thanks about reply. I Mean this control
http://examples.ext.net/#/Desktop/Introduction/Overview/
when you open a window in desktop control and load a user control that contains Persian calendar control in it's content (Loading user control that contains Persian calendar in content of a window that is contained in desktop control), it will return this error. In this scenario the Persian calendar controls can not find embedded java scripts. I don't know why!!!!

**Comment by hogaf** [comment]
Please use the other repository named "Hogaf.ExtNet3.UX".

**Comment by ArashRahimian** [comment]
Ok. TX
